
name: CI

on: push

jobs:
  job1:
    name: Job 1
    outputs:
      prefix: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 1
        run: echo "Run Job 1"

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  job2:
    name: Job 2
    outputs:
      prefix: ${{ steps.set_output.outputs.dir_prefix }}
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: set_output
        run: echo "::set-output name=dir_prefix::${{ github.workspace }}"

  job3:
    name: Job 3
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: view the outputs of job1 and job2
        run: |
          echo "needs.job1.outputs.prefix = ${{ needs.job1.outputs.prefix }}"
          echo "needs.job2.outputs.prefix = ${{ needs.job2.outputs.prefix }}"
