name: PR with path

on:
  pull_request:
    paths:
      - '**'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
